### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by ghost** [clarionut/TM_LPG-MIX#1]
The file `TM_LPG-MIX_cache.lib` is missing causing some symbols to be missing in the schematic editor

![image](https://github.com/clarionut/TM_LPG-MIX/assets/56895621/37653322-1c68-4072-b2d6-2ceb7671b49c)

**Comment by clarionut** [comment]
Sorry about that! I've uploaded the cache-lib file. I'm a bit puzzled about the items that are missing - on the main schematic they're male connectors and one of the items missing in the front panel box is simply a potentiometer. The other panel items are customised audio jack symbols. I've added a copy of my custom symbols library too. Hope this fixes the issue.

**Comment by ghost** [comment]
Yes, the jacks were from your custom  symbols. As for the pot and the headers, I'm using KiCad 7 and those now have different names (R_Pot became R_Potentiometer and Conn_nnxmm_Male became Conn_nnxmm_Pin) so it didn't know what those were without the symbols cache.
